2024-12-01 03:01:44,646 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\pahan\PycharmProjects\Python Projects\mod_12\test_12_2\tests_12_4.py", line 28, in test_run
    t2 = test.Runner(2)
  File "C:\Users\pahan\PycharmProjects\Python Projects\mod_12\test_12_2\run_12_4.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-01 03:01:44,648 | INFO | "test_run" выполнен успешно
2024-12-01 03:01:44,648 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\pahan\PycharmProjects\Python Projects\mod_12\test_12_2\tests_12_4.py", line 18, in test_walk
    t1 = test.Runner('Вася', -5)
  File "C:\Users\pahan\PycharmProjects\Python Projects\mod_12\test_12_2\run_12_4.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
2024-12-01 03:01:44,649 | INFO | "test_walk" выполнен успешно
